name: Cowsay Dragon Workflow

on:
    push:
    workflow_dispatch:

jobs:
    build-job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update apt-get
              run: sudo apt-get update

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for Cover, I'm a dragon ... RAWR" >> dragon.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: dragon-file
                  path: dragon.txt

            - name: List files in the repository
              run: ls -l
